version: '3.7'
services:
  db:
    container_name: db
    image: postgres:latest
    env_file: container/database.conf
    ports:
      - 5432:5432  
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  testdb:
    container_name: testdb
    image: postgres:latest
    env_file: container/database_test.conf
  web:
    container_name: flask_app
    build:
      context: .
      dockerfile: container/flask/Dockerfile
    volumes: 
      - .:/srv/flask_app
    env_file: .env
    command: python manage.py db init
    command: python manage.py db migrate
    depends_on:
     - db
     - testdb
    restart: unless-stopped