version: '3.7'
services:
  db:
    container_name: db
    image: postgres:latest
    env_file: container/database.conf
    ports:
      - 5432:5432  
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  testdb:
    container_name: testdb
    image: postgres:latest
    env_file: container/database_test.conf
  web:
    container_name: flask_app
    build:
      context: .
      dockerfile: container/flask/Dockerfile
    volumes: 
      - .:/srv/flask_app
    env_file: .env
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    depends_on:
     - db
     - testdb
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web