version: '3.7'
services:
  db:
    image: postgres:latest
    env_file: container/database.conf
    ports:
      - 5432:5432  
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  testdb:
    image: postgres:latest
    env_file: container/database_test.conf
  web:
    build:
      context: .
      dockerfile: container/flask/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes: 
      - .:/srv/flask_app
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
     - db
     - testdb
    restart: unless-stopped